### ISSUE TITLE
Design - Does this code follow the clean arch by Uncle bob

### ISSUE THREAD

**Issue by alok87** [ribice/gorsk#61]
- What are the layers you have in this codebase?
- If it follows/matches Clean arch by Uncle Bob - https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html

What are the layers here, could you please explain the code architecture a little bit. Which layer talks to which layer and which one is outer most layer and which one here are the inner most?

**Comment by ribice** [comment]
There are three layers in this codebase:

1. Transport layer: It gets the data via HTTP / REST endpoints, validates it and passes it down to the application service. Look for `package transport`.

2. Application service layer: This is where the application/business logic resides. Calling database, third party services, storage, authorization is done here. The package is named after the service, for example `package user`.

3. Repository/database layer is found in `package pgsql`.

4. This is all wired up in `pkg/api/api.go`

5. Models (since I'm using ORM) are found in `pkg/utl/model` although I dislike the location of package and may migrate it to another place.
