### ISSUE TITLE
Q: Why echo, not Chi?

### ISSUE THREAD

**Issue by rrjanbiah** [ribice/gorsk#76]
Just curious....

According to https://www.ribice.ba/golang-web-frameworks/ article, you're suggesting `Chi` is better than `echo`. But, looks like you've rewritten it with `echo` instead. Can you please share the thought process? TIA

**Comment by padurean** [comment]
@rrjanbiah I think the answer (kind of, at least) is at the end of the very same blog article:

> Also, I have plans to rewrite Gorsk yet again, this time in Chi. Chi seems quite close to stdlib that I may actually stick with it for a while. Time will tell.

**Comment by rrjanbiah** [comment]
@padurean Yes, but he rewrote it in echo (from gin), instead of Chi (if I'm right).

**Comment by ribice** [comment]
I build most of my new projects using Chi (or gorilla/mux), and haven't used Echo since Gorsk.

I don't have time to rewrite Gorsk, so it'll stay most probably with Echo indefinitely.

**Comment by rrjanbiah** [comment]
@ribice Thanks a lot for your note

**Comment by wangyoucao577** [comment]
Excellent post and discussion!        
I have thought among these three frameworks too months ago, and eventually I also picked up Chi, mostly due to below reasons:    
- lightweight
- 100% compatible with `net/http`
- workable with [deepmap/oapi-codegen](https://github.com/deepmap/oapi-codegen) so that I can generate codes from openapi v3.
